title: "カービィ"

lang: ja
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

locale: ja_JP
title_separator: "|"
minimal_mistakes_skin: "air" # 全体の色合い

breadcrumbs: true
logo: "/assets/images/png-transparent-kirby-s-return-to-dream-land-kirby-air-ride-kirby-planet-robobot-kirby-triple-deluxe-kirby-s-epic-yarn-kirby-game-nintendo-eating-thumbnail.png"
include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      header:
        overlay_image: /assets/images/rectangle_large_type_2_22b196fe8a67550735351089b16124d1.png
        overlay_filter: 0.5
  # pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      author: default

theme: jekyll-theme-slate
